# Generated by Django 3.2.5 on 2022-02-18 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20220217_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_by', to='catalog.librarian'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='librarian',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.librarian'),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='django_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
