# Generated by Django 3.2.5 on 2022-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220218_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email_field',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='home_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
