# Generated by Django 3.2.5 on 2022-03-13 07:26

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_borrower_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='idcard',
            field=models.FileField(blank=True, upload_to=catalog.models.user_directory_path),
        ),
    ]
